### ISSUE TITLE
cmy_image.py fails to run

### ISSUE THREAD

**Issue by anntzer** [newville/wxmplot#28]
Trying to run `cmy_image.py` fails with
```
Traceback (most recent call last):
  File "cmy_image.py", line 35, in <module>
    subtitles={'cyan':'Cyan Image', 'magenta': 'Magenta Blob', 'yellow': 'other'})
  File "/home/antony/src/extern/wxmplot/build/lib/wxmplot/imageframe.py", line 443, in display
    self.set_subtitles(**subtitles)
TypeError: set_subtitles() got an unexpected keyword argument 'cyan'
```

**Comment by newville** [comment]
@anntzer Thanks -- I was recently trying to allow  CMY variation for 3-color maps, but apparently this did not get completed!  Will try to fix soon.
